# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jirka < Formula
  desc "TUI dashboard for Jira tickets"
  homepage "https://github.com/cnwv/jirka"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cnwv/jirka/releases/download/v0.3.1/jirka_0.3.1_darwin_amd64.tar.gz"
      sha256 "7e2d4f0062cd84442b0c07bf3f669588e24737c0a4dac01c89f8d8e5b75f410c"

      define_method(:install) do
        bin.install "jirka"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cnwv/jirka/releases/download/v0.3.1/jirka_0.3.1_darwin_arm64.tar.gz"
      sha256 "ea4001f863261a598d3bca03155fc7231f4ab6ab43198848410bb792753bd39b"

      define_method(:install) do
        bin.install "jirka"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cnwv/jirka/releases/download/v0.3.1/jirka_0.3.1_linux_amd64.tar.gz"
      sha256 "cd79aa67a6eaf7af5fca333f6c67bc219d79e712390759e316f9bd7699bc04f2"
      define_method(:install) do
        bin.install "jirka"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cnwv/jirka/releases/download/v0.3.1/jirka_0.3.1_linux_arm64.tar.gz"
      sha256 "bded56ec868f9e7f06e969eac4505fc110533c9dcf222eb436128d408d90378a"
      define_method(:install) do
        bin.install "jirka"
      end
    end
  end
end
