# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jirka < Formula
  desc "TUI dashboard for Jira tickets"
  homepage "https://github.com/cnwv/jirka"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cnwv/jirka/releases/download/v0.1.0/jirka_0.1.0_darwin_amd64.tar.gz"
      sha256 "dce2f377d4bf280389405aa0bdd2089bef6acec96076b78dadb58f7320760be8"

      define_method(:install) do
        bin.install "jirka"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cnwv/jirka/releases/download/v0.1.0/jirka_0.1.0_darwin_arm64.tar.gz"
      sha256 "f2b82ef176cf082bc4102071f00ee6ce83e4a07eaf786758d74be8fae4431792"

      define_method(:install) do
        bin.install "jirka"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cnwv/jirka/releases/download/v0.1.0/jirka_0.1.0_linux_amd64.tar.gz"
      sha256 "9ea4bcc78823b4c032e369b9790408ebe6e0d248c286ef0e7a5e4ca75d74795f"
      define_method(:install) do
        bin.install "jirka"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cnwv/jirka/releases/download/v0.1.0/jirka_0.1.0_linux_arm64.tar.gz"
      sha256 "cbaaa7a14acf5ed781d77ffc5b3c4e73f65a6db4904a727c501c9f5ab492e7d6"
      define_method(:install) do
        bin.install "jirka"
      end
    end
  end
end
